### ISSUE TITLE
List of files/blob

### ISSUE THREAD

**Issue by kethan** [feathersjs/feathers-blob#5]
How do I get the list?

**Comment by ComputerCarl** [comment]
...or I might expand on what @kethan is asking;
I am just learning Feathers, so forgive if the is a noob question.

Would this be considered a "typical" Feathers "service"? Is there really any method other than `create`? You wouldn't be applying other methods such as `update`  or `find` or even query this service in any way but rather directly with the filesystem? The reason that I am confused is that I believe I read somewhere that every feathers service has specific methods;
````js
// reference:
var myService = {
  find: function(params, callback) {},
  get: function(id, params, callback) {},
  create: function(data, params, callback) {},
  update: function(id, data, params, callback) {},
  updateMany: function(data, params, callback) {},
  patch: function(id, data, params, callback) {},
  patchMany: function(data, params, callback) {},
  remove: function(id, params, callback) {},
  removeMany: function(params, callback) {},
  setup: function(app) {}
}
````

Would it be correct to say that a second service, such as a `media` db service is needed to add information, such as the owner, and the upload file "service" would be invoked when creating a new `media` object?

**Comment by daffl** [comment]
Anything that has at least one of those methods is considered a service but yes, if you want to store additional metadata you create a separate service to store those (as well as getting a list of media).

To answer the original question, the [abstract blob store](https://github.com/maxogden/abstract-blob-store) does not include any functionality to list all files (probably because some of the supported storages don't). As mentioned, the solution would be to store and list metadata in a separate database backed service.
